#!/usr/bin/env python3
import papis.api as p
import papis
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
import clipboard

docs = []
headers = ["Author", "Title", "Year", "ref"]
rows = []
texts = []

def load_texts(lib):
    global docs
    for j,i in enumerate(docs):
        fldr = i.get_main_folder()
        ftext = ""
        try:
            with open(f"{fldr}/text.txt", "r") as f:
                ftext = f.read()
        except:
            pass
        docs[j]['full_text'] = ftext

def load_docs(lib):
    global docs
    global rows
    docs = p.get_all_documents_in_lib(lib)
    rows = [(a['author'], a['title'], a['year'], a['ref']) for a in docs]
    load_texts(lib)


def docbyref(ref):
    for d in docs:
        if d['ref'] == ref:
            return d

load_docs(p.get_lib_name())

class TableModel(QAbstractTableModel):
    def rowCount(self, parent):
        return len(rows)
    def columnCount(self, parent):
        return len(headers)
    def data(self, index, role):
        if role != Qt.DisplayRole:
            return QVariant()
        return rows[index.row()][index.column()]
    def headerData(self, section, orientation, role):
        if role != Qt.DisplayRole or orientation != Qt.Horizontal:
            return QVariant()
        return headers[section]

class FilMo(QSortFilterProxyModel):
    def filterAcceptsRow(self, srow, sparent):
        bigbool = False
        re = str(self.filterRegExp().pattern()).lower()
        for i, d in enumerate(headers[:-1]):
            colstr = str(self.sourceModel().index(srow,i).data()).lower()
            #print(re in colstr)
            bigbool = bigbool or (re in colstr)
        return bigbool

class FilMo2(QSortFilterProxyModel):
    def filterAcceptsRow(self, srow, sparent):
        re = str(self.filterRegExp().pattern()).lower()
        ref = str(self.sourceModel().index(srow,3).data())
        doc = docbyref(ref)
        return re in doc['full_text'].lower()


def click_row(e):
    sm = view.selectionModel()
    idx = sm.selectedRows()[0].row()
    ref = filtermodel.index(idx,len(headers)-1).data()
    doc = docbyref(ref)
    p.open_file(doc.get_files()[0])

def open_menu(pos):
    sm = view.selectionModel()
    #idxs = sm.selectedRows()[0].row()
    idxs = sm.selectedRows()
    docs = []
    for i in idxs:
        idx = i.row()
        ref = filtermodel.index(idx,len(headers)-1).data()
        doc = docbyref(ref)
        docs.append(doc)
    menu = QMenu()
    exportAction = menu.addAction("Export")
    action = menu.exec_(view.mapToGlobal(pos))
    if action == exportAction:
        bibtex = papis.bibtex.exporter(docs)
        clipboard.copy(bibtex)


app = QApplication([])
#window = QWidget()


def onkey2(e):
    QLineEdit.keyPressEvent(sbar2,e)
    txt = sbar2.text()
    filtermodel.setFilterFixedString(txt)

def onkey(e):
    QLineEdit.keyPressEvent(sbar,e)
    txt = sbar.text()
    interfiltermodel.setFilterFixedString(txt)

def onlibchange(e):
    model.beginResetModel()
    newlib = libpicker.currentText()
    load_docs(newlib)
    model.endResetModel()
    view.reset()

mainlayout = QVBoxLayout()
model = TableModel()
view = QTableView()

sbar = QLineEdit()
sbar2 = QLineEdit()
sbar.setPlaceholderText("Search Metadata")
sbar2.setPlaceholderText("Search In")
libpicker = QComboBox()
libpicker.addItems(p.get_libraries())
libpicker.setCurrentText(p.get_lib_name())
libpicker.currentTextChanged.connect(onlibchange)
sbar.keyPressEvent = onkey
sbar2.keyPressEvent = onkey2
mainlayout.addWidget(libpicker)
mainlayout.addWidget(sbar)
mainlayout.addWidget(sbar2)
#filtermodel = QSortFilterProxyModel()
interfiltermodel = FilMo(None)
interfiltermodel.setSourceModel(model)
interfiltermodel.setFilterFixedString("")
#interfiltermodel.setFilterCaseSensitivity(Qt.CaseSensitivity.CaseInsensitive)
filtermodel = FilMo2(None)
filtermodel.setSourceModel(interfiltermodel)
filtermodel.setFilterFixedString("")

view.setSelectionBehavior(QAbstractItemView.SelectRows)
view.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
view.setModel(filtermodel)
#view.horizontalHeader().setSectionResizeMode(QHeaderView.Fixed)
view.verticalHeader().setSectionResizeMode(QHeaderView.Fixed)
view.verticalHeader().setVisible(False)
view.setColumnHidden(len(headers)-1, True)
view.setContextMenuPolicy(Qt.CustomContextMenu)
view.customContextMenuRequested.connect(open_menu)
view.mouseDoubleClickEvent = click_row
mainlayout.addWidget(view)

qw = QWidget()
qw.setLayout(mainlayout)
qw.show()
sbar.setFocus()
app.exec_()
